;;; modelmux-tests.el --- Tests for ModelMux -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'modelmux)

(defun modelmux-test--task (id &optional status name)
  `((id . ,id)
    (name . ,(or name id))
    (task . "tts")
    (profile . "qwen3-tts-0.6b-base-8bit")
    (status . ,(or status "completed"))
    (progress . 100)
    (message . "Completed")
    (artifact_url . ,(format "/v1/jobs/%s/artifact" id))
    (created_at . "2026-09-03T10:00:00+00:00")
    (started_at . "2026-09-03T10:00:01+00:00")
    (finished_at . "2026-09-03T10:00:04+00:00")))

(ert-deftest modelmux-buffer-text-uses-whole-buffer-without-region ()
  (with-temp-buffer
    (insert "whole buffer")
    (should (equal (modelmux--buffer-text) "whole buffer"))))

(ert-deftest modelmux-buffer-text-prefers-active-region ()
  (with-temp-buffer
    (transient-mark-mode 1)
    (insert "before selected after")
    (goto-char 8)
    (push-mark 16 t t)
    (should (equal (modelmux--buffer-text) "selected"))))

(ert-deftest modelmux-speak-submits-selected-text ()
  (with-temp-buffer
    (insert "text to speak")
    (let (started tasks-shown)
      (cl-letf (((symbol-function 'modelmux--submit-text-run)
                 (lambda (&rest arguments) (setq started arguments)))
                ((symbol-function 'modelmux-tasks)
                 (lambda () (setq tasks-shown t))))
        (modelmux-speak))
      (should (equal started
                     (list "tts" modelmux-tts-profile "text to speak")))
      (should tasks-shown))))

(ert-deftest modelmux-transcribe-submits-selected-audio-file ()
  (let (started tasks-shown)
    (cl-letf (((symbol-function 'file-regular-p) (lambda (_file) t))
              ((symbol-function 'modelmux--submit-file-run)
               (lambda (&rest arguments) (setq started arguments)))
              ((symbol-function 'modelmux-tasks)
               (lambda () (setq tasks-shown t))))
      (modelmux-transcribe "/tmp/recording.wav"))
    (should (equal started
                   (list "asr" modelmux-asr-profile "/tmp/recording.wav")))
    (should tasks-shown)))

(ert-deftest modelmux-transcribe-file-picker-keeps-directories-visible ()
  (let (read-arguments)
    (cl-letf (((symbol-function 'read-file-name)
               (lambda (&rest arguments)
                 (setq read-arguments arguments)
                 "/tmp/recording.wav"))
              ((symbol-function 'file-regular-p) (lambda (_file) t))
              ((symbol-function 'modelmux--submit-file-run) #'ignore)
              ((symbol-function 'modelmux-tasks) #'ignore))
      (call-interactively #'modelmux-transcribe))
    (should (nth 3 read-arguments))
    (should-not (nth 5 read-arguments))))

(ert-deftest modelmux-text-run-submits-directly-to-http-api ()
  (let (request)
    (cl-letf (((symbol-function 'modelmux--http-json-async)
               (lambda (method path payload _callback)
                 (setq request (list method path payload)))))
      (modelmux--submit-text-run "tts" "voice" "文章"))
    (should (equal (seq-take request 2) '("POST" "/v1/jobs")))
    (should (equal (alist-get 'task (nth 2 request)) "tts"))
    (should (equal (alist-get 'model (nth 2 request)) "voice"))
    (should (equal (alist-get 'input (nth 2 request)) "文章"))))

(ert-deftest modelmux-upload-url-escapes-profile-name ()
  (let ((modelmux-base-url "http://127.0.0.1:8765/"))
    (should (equal (modelmux--upload-url "asr" "a model")
                   "http://127.0.0.1:8765/v1/jobs/upload?task=asr&model=a%20model"))))

(ert-deftest modelmux-task-entry-is-compact ()
  (let* ((modelmux--tasks (list (modelmux-test--task "abc")))
         (cells (cadar (modelmux--task-entries))))
    (should (= (length cells) 6))
    (should (equal (aref cells 0) "abc"))
    (should (equal (aref cells 1) "TTS"))
    (should (equal (substring-no-properties (aref cells 3)) "✓ Ready"))
    (should (equal (aref cells 5) "3s"))))

(ert-deftest modelmux-progress-cell-renders-a-bar ()
  (should (equal (modelmux--progress-cell 50) "██████░░░░░░  50%")))

(ert-deftest modelmux-task-refresh-preserves-row-column-and-mark ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-tasks*")
         (task (modelmux-test--task "run-7" "running"))
         (modelmux--tasks (list task)))
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (tabulated-list-print t)
          (modelmux--goto-task-id "run-7")
          (move-to-column 9)
          (let ((column (current-column)))
            (puthash "run-7" t modelmux--marked)
            (modelmux--print-preserving-position)
            (should (equal (tabulated-list-get-id) "run-7"))
            (should (= (current-column) column))
            (should (gethash "run-7" modelmux--marked))
            (should (overlays-at (line-beginning-position)))))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-task-rename-goes-through-http ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-rename*")
         (task (modelmux-test--task "run-a"))
         (modelmux--tasks (list task))
         calls)
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (tabulated-list-print t)
          (modelmux--goto-task-id "run-a")
          (cl-letf (((symbol-function 'read-string)
                     (lambda (&rest _arguments) "Article"))
                    ((symbol-function 'modelmux--http-json-sync)
                     (lambda (&rest arguments)
                       (push arguments calls)
                       task))
                    ((symbol-function 'modelmux-tasks-refresh) #'ignore))
            (modelmux-task-rename))
          (should (member '("PATCH" "/v1/jobs/run-a" ((name . "Article")))
                          calls)))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-task-delete-uses-marked-ids ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-delete*")
         (tasks (list (modelmux-test--task "run-a")
                      (modelmux-test--task "run-b")))
         (modelmux--tasks tasks)
         calls)
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (puthash "run-a" t modelmux--marked)
          (puthash "run-b" t modelmux--marked)
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                    ((symbol-function 'modelmux--http-json-sync)
                     (lambda (&rest arguments)
                       (push arguments calls)
                       nil))
                    ((symbol-function 'modelmux-tasks-refresh) #'ignore))
            (modelmux-task-delete))
          (should (member '("POST" "/v1/jobs/delete"
                            ((ids . ["run-a" "run-b"])))
                          calls))
          (should (= (hash-table-count modelmux--marked) 0)))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-batch-commands-send-json-arrays ()
  (dolist (command '(modelmux-task-delete modelmux-task-cancel))
    (dolist (ids '(("715db159a2ca43ebaf64a7dd3995afca")
                   ("715db159a2ca43ebaf64a7dd3995afca" "another-run")))
      (with-temp-buffer
        (let ((modelmux--marked (make-hash-table :test 'equal))
              sent)
          (cl-letf (((symbol-function 'modelmux--selected-task-ids)
                     (lambda () ids))
                    ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                    ((symbol-function 'modelmux-tasks-refresh) #'ignore)
                    ((symbol-function 'url-retrieve-synchronously)
                     (lambda (&rest _)
                       (setq sent (json-parse-string
                                   (decode-coding-string url-request-data 'utf-8)
                                   :object-type 'alist))
                       (let ((response (generate-new-buffer " *modelmux-reply*")))
                         (with-current-buffer response
                           (insert "HTTP/1.1 200 OK\r\n\r\n{}"))
                         response))))
            (funcall command))
          (should (equal (alist-get 'ids sent) (vconcat ids))))))))

(ert-deftest modelmux-http-body-start-skips-response-headers ()
  (with-temp-buffer
    (insert "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{}")
    ;; With no `url-http-end-of-headers', the blank line must be found by search.
    (should (equal (buffer-substring (modelmux--http-body-start) (point-max))
                   "{}"))))

(ert-deftest modelmux-http-error-response-signals-a-user-error ()
  (with-temp-buffer
    (insert "\r\n\r\n{\"error\": {\"message\": \"Unknown profile\"}}")
    (setq-local url-http-response-status 400)
    (should-error (modelmux--http-json-from-current-buffer) :type 'user-error)))

(ert-deftest modelmux-mark-region-excludes-a-trailing-empty-line ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-marks*")
         (modelmux--tasks (list (modelmux-test--task "run-a")
                                (modelmux-test--task "run-b"))))
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (tabulated-list-print t)
          (modelmux--goto-task-id "run-a")
          ;; A region ending exactly at the second row's start marks only the first.
          (modelmux--mark-region (point) (save-excursion (forward-line 1) (point)))
          (should (gethash "run-a" modelmux--marked))
          (should-not (gethash "run-b" modelmux--marked)))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-prune-marks-drops-ids-absent-from-the-response ()
  (with-temp-buffer
    (setq-local modelmux--marked (make-hash-table :test 'equal))
    (puthash "gone" t modelmux--marked)
    (puthash "run-a" t modelmux--marked)
    (let ((modelmux--tasks (list (modelmux-test--task "run-a"))))
      (modelmux--prune-marks))
    (should (gethash "run-a" modelmux--marked))
    (should-not (gethash "gone" modelmux--marked))))

(ert-deftest modelmux-refresh-skips-redraw-for-unchanged-finished-runs ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-idle*")
         (tasks (list (modelmux-test--task "run-a"))))
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (setq modelmux--tasks tasks)
          (let (redrawn)
            (cl-letf (((symbol-function 'modelmux--print-preserving-position)
                       (lambda () (setq redrawn t))))
              (modelmux--accept-tasks (copy-tree tasks))
              (should-not redrawn)
              ;; A running task advances its elapsed time, so it must redraw.
              (modelmux--accept-tasks (list (modelmux-test--task "run-a" "running")))
              (should redrawn))))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-refresh-guard-clears-after-every-request ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-guard*")
         calls)
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (cl-letf (((symbol-function 'modelmux--http-json-async)
                     (lambda (_method _path _payload callback &optional finally)
                       (push t calls)
                       (funcall callback nil)
                       (when finally (funcall finally)))))
            (modelmux-tasks-refresh)
            (should-not modelmux--refresh-in-flight)
            ;; The guard released, so a second refresh must issue a request.
            (modelmux-tasks-refresh)
            (should (= (length calls) 2))))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-http-async-runs-finally-when-request-cannot-start ()
  (let (finished)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (&rest _arguments) (error "cannot start"))))
      (modelmux--http-json-async
       "GET" "/v1/jobs" nil #'ignore (lambda () (setq finished t))))
    (should finished)))

(ert-deftest modelmux-artifact-download-reuses-the-local-copy ()
  (let* ((root (make-temp-file "modelmux-test-" t))
         (temporary-file-directory root)
         (modelmux--tasks-buffer " *modelmux-test-artifact*")
         (task (modelmux-test--task "run-a"))
         (modelmux--tasks (list task))
         (path (expand-file-name "modelmux/run-a/artifact.wav" root))
         opened)
    (unwind-protect
        (progn
          (make-directory (file-name-directory path) t)
          (write-region "audio" nil path nil 'silent)
          (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
            (modelmux-tasks-mode)
            (tabulated-list-print t)
            (modelmux--goto-task-id "run-a")
            (cl-letf (((symbol-function 'make-process)
                       (lambda (&rest _) (ert-fail "unexpected download"))))
              (modelmux--download-artifact (lambda (value) (setq opened value)))))
          (should (equal opened path)))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer))
      (delete-directory root t))))

;;; modelmux-tests.el ends here
