;;; modelmux-tests.el --- Tests for ModelMux -*- lexical-binding: t; -*-

(require 'ert)
(require 'modelmux)

(defun modelmux-test--task (id &optional status name)
  `((id . ,id)
    (name . ,(or name id))
    (task . "tts")
    (profile . "qwen3-tts-0.6b-base-8bit")
    (status . ,(or status "completed"))
    (progress . 100)
    (message . "Completed")
    (artifact . ,(format "/tmp/%s.wav" id))
    (created_at . "2026-09-03T10:00:00+00:00")
    (started_at . "2026-09-03T10:00:01+00:00")
    (finished_at . "2026-09-03T10:00:04+00:00")))

(ert-deftest modelmux-buffer-text-uses-whole-buffer-without-region ()
  (with-temp-buffer
    (insert "whole buffer")
    (should (equal (modelmux--buffer-text) "whole buffer"))))

(ert-deftest modelmux-buffer-text-prefers-active-region ()
  (with-temp-buffer
    (transient-mark-mode 1)
    (insert "before selected after")
    (goto-char 8)
    (push-mark 16 t t)
    (should (equal (modelmux--buffer-text) "selected"))))

(ert-deftest modelmux-speak-starts-python-run-without-callback ()
  (with-temp-buffer
    (insert "text to speak")
    (let (started)
      (cl-letf (((symbol-function 'modelmux--start-run)
                 (lambda (&rest arguments) (setq started arguments))))
        (modelmux-speak))
      (should (equal started
                     (list "tts" "text to speak" modelmux-tts-profile))))))

(ert-deftest modelmux-task-entry-is-compact ()
  (let* ((modelmux--tasks (list (modelmux-test--task "abc")))
         (cells (cadar (modelmux--task-entries))))
    (should (= (length cells) 6))
    (should (equal (aref cells 0) "abc"))
    (should (equal (aref cells 1) "TTS"))
    (should (equal (substring-no-properties (aref cells 3)) "✓ Ready"))
    (should (equal (aref cells 5) "3s"))))

(ert-deftest modelmux-tasks-mode-has-management-bindings ()
  (should (eq (lookup-key modelmux-tasks-mode-map (kbd "o"))
              #'modelmux-task-open-externally))
  (should (eq (lookup-key modelmux-tasks-mode-map (kbd "O"))
              #'modelmux-task-open-directory))
  (should (eq (lookup-key modelmux-tasks-mode-map (kbd "e"))
              #'modelmux-task-rename))
  (should (eq (lookup-key modelmux-tasks-mode-map (kbd "D"))
              #'modelmux-task-delete))
  (should (eq (lookup-key modelmux-tasks-mode-map (kbd "m"))
              #'modelmux-task-mark)))

(ert-deftest modelmux-progress-cell-renders-a-bar ()
  (should (equal (modelmux--progress-cell 50) "██████░░░░░░  50%")))

(ert-deftest modelmux-task-refresh-preserves-row-column-and-mark ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-tasks*")
         (task (modelmux-test--task "run-7" "running"))
         (modelmux--tasks (list task)))
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (tabulated-list-print t)
          (modelmux--goto-task-id "run-7")
          (move-to-column 9)
          (let ((column (current-column)))
            (puthash "run-7" t modelmux--marked)
            (modelmux--print-preserving-position)
            (should (equal (tabulated-list-get-id) "run-7"))
            (should (= (current-column) column))
            (should (gethash "run-7" modelmux--marked))
            (should (overlays-at (line-beginning-position)))))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-task-rename-goes-through-cli ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-rename*")
         (task (modelmux-test--task "run-a"))
         (modelmux--tasks (list task))
         calls)
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (tabulated-list-print t)
          (modelmux--goto-task-id "run-a")
          (cl-letf (((symbol-function 'read-string)
                     (lambda (&rest _arguments) "Article"))
                    ((symbol-function 'modelmux--call-json)
                     (lambda (&rest arguments)
                       (push arguments calls)
                       task))
                    ((symbol-function 'modelmux-tasks-refresh) #'ignore))
            (modelmux-task-rename))
          (should (member '("runs" "rename" "run-a" "Article" "--json") calls)))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

(ert-deftest modelmux-task-delete-uses-marked-ids ()
  (let* ((modelmux--tasks-buffer " *modelmux-test-delete*")
         (tasks (list (modelmux-test--task "run-a")
                      (modelmux-test--task "run-b")))
         (modelmux--tasks tasks)
         calls)
    (unwind-protect
        (with-current-buffer (get-buffer-create modelmux--tasks-buffer)
          (modelmux-tasks-mode)
          (puthash "run-a" t modelmux--marked)
          (puthash "run-b" t modelmux--marked)
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                    ((symbol-function 'modelmux--call-json)
                     (lambda (&rest arguments)
                       (push arguments calls)
                       nil))
                    ((symbol-function 'modelmux-tasks-refresh) #'ignore))
            (modelmux-task-delete))
          (should (member '("runs" "delete" "run-a" "run-b" "--json") calls))
          (should (= (hash-table-count modelmux--marked) 0)))
      (when (get-buffer modelmux--tasks-buffer)
        (kill-buffer modelmux--tasks-buffer)))))

;;; modelmux-tests.el ends here
